import type { Testimonial } from "@/types";

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "testimonial-001",
    name: "MCR",
    rating: 5,
    text: "Acudí para una segunda opinión y me dio mucha confianza la manera en la que me explicó mi problema, noté que domina muy bien el tema y me operé con él, lo recomiendo sin duda.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-002",
    name: "Alejandra Reyes Coronado",
    rating: 5,
    text: "La atención fue de calidad, fue puntual y profesional. Lo recomiendo.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-003",
    name: "AMDC",
    rating: 5,
    text: "Excelente atención, explicación clara y entendible. Muy formal el doctor.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-004",
    name: "DRH",
    rating: 5,
    text: "El doctor es muy profesional y el mejor explicando el padecimiento. Resolvió todas mis dudas y el tratamiento que me dio fue el indicado. Sin duda lo recomiendo.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-005",
    name: "BR",
    rating: 5,
    text: "Puntual y con buena disposición. Atento y empático, se toma el tiempo para explicar tu enfermedad y el tratamiento que requieres.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-006",
    name: "Miguel Ángel Pérez Cruz",
    rating: 5,
    text: "Después de mi cirugía de hernia, la recuperación fue muy rápida y el seguimiento cercano, gran empatía del doctor Mario. Muy agradecido por la atención.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-007",
    name: "Daniela Torres Hernandez",
    rating: 5,
    text: "Muy buena experiencia. Fui atendido por una hernia y el trato fue impecable, siempre explicando todo con calma.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-008",
    name: "PaolaCamacho",
    rating: 5,
    text: "El doctor se toma su tiempo para explicar a detalle la enfermedad y cómo realizará la cirugía. Muy contenta con su servicio.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-009",
    name: "Majo Padilla",
    rating: 5,
    text: "Muy agradecida por el trato a mi papá en su cirugía de urgencia.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-010",
    name: "Alejandro Ramirez García",
    rating: 5,
    text: "El doctor Mario fue muy respetuoso y atento durante la explicación de mi enfermedad, después de la cirugía las molestias fueron mínimas. Lo recomiendo mucho.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
];
