import type { Testimonial } from "@/types";

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "testimonial-001",
    name: "María Elena Gutiérrez",
    age: 42,
    procedure: "Manga Gástrica",
    rating: 5,
    text: "Después de años luchando con mi peso, el Dr. Mario me devolvió la confianza en mí misma. La manga gástrica cambió mi vida por completo y el seguimiento postoperatorio fue excepcional. Hoy me siento más saludable y con una energía que no tenía desde mis veintes.",
    weightLost: "45 kg",
    timeAgo: "Hace 8 meses",
  },
  {
    id: "testimonial-002",
    name: "Roberto Alejandro Pérez",
    age: 55,
    procedure: "Bypass Gástrico",
    rating: 5,
    text: "Tenía diabetes tipo 2 y mi endocrinólogo me recomendó al Dr. Ruvalcaba. Después del bypass gástrico, mis niveles de glucosa se normalizaron en pocas semanas. Estoy eternamente agradecido con todo el equipo médico por su profesionalismo y calidez humana.",
    weightLost: "52 kg",
    timeAgo: "Hace 1 año",
  },
  {
    id: "testimonial-003",
    name: "Lucía Fernanda Castillo",
    age: 34,
    procedure: "Balón Intragástrico",
    rating: 4,
    text: "Elegí el balón intragástrico porque buscaba una opción menos invasiva. El procedimiento fue rápido y la recuperación muy llevadera. Perdí peso de manera gradual y aprendí hábitos alimenticios que mantengo hasta hoy.",
    weightLost: "22 kg",
    timeAgo: "Hace 6 meses",
  },
  {
    id: "testimonial-004",
    name: "Jorge Antonio Medina",
    age: 48,
    procedure: "Manga Gástrica",
    rating: 5,
    text: "Vine desde Cancún específicamente para operarme con el Dr. Mario. Desde la primera consulta me sentí en confianza y seguro. La cirugía fue un éxito y el equipo de nutrición me ha acompañado en cada paso de mi transformación.",
    weightLost: "38 kg",
    timeAgo: "Hace 10 meses",
  },
  {
    id: "testimonial-005",
    name: "Ana Patricia Domínguez",
    age: 39,
    procedure: "Bypass Gástrico",
    rating: 5,
    text: "Después de intentar todo tipo de dietas sin resultados duraderos, el bypass gástrico fue la mejor decisión de mi vida. El Dr. Ruvalcaba explicó cada detalle del procedimiento con mucha paciencia. Ya no sufro de apnea del sueño ni de dolor en las rodillas.",
    weightLost: "48 kg",
    timeAgo: "Hace 1 año y 2 meses",
  },
  {
    id: "testimonial-006",
    name: "Carlos Eduardo Vargas",
    age: 31,
    procedure: "Balón Intragástrico",
    rating: 4,
    text: "A mis 31 años ya tenía problemas de hipertensión por el sobrepeso. El balón intragástrico me ayudó a bajar de peso de forma controlada. El seguimiento nutricional y psicológico que ofrece el Dr. Mario fue clave para mantener mis resultados.",
    weightLost: "19 kg",
    timeAgo: "Hace 4 meses",
  },
  {
    id: "testimonial-007",
    name: "Guadalupe Sánchez Herrera",
    age: 58,
    procedure: "Cirugía de Mínima Invasión",
    rating: 5,
    text: "A mi edad tenía muchos miedos, pero el Dr. Ruvalcaba me dio toda la confianza con su experiencia y trato humano. La cirugía de mínima invasión hizo que mi recuperación fuera mucho más rápida de lo que esperaba. Hoy camino diario y disfruto la vida al máximo.",
    weightLost: "35 kg",
    timeAgo: "Hace 7 meses",
  },
  {
    id: "testimonial-008",
    name: "Fernando Isaías Torres",
    age: 44,
    procedure: "Manga Gástrica",
    rating: 5,
    text: "Soy de Estados Unidos y elegí Mérida para mi cirugía bariátrica por la calidad y el precio. El Dr. Mario superó todas mis expectativas; las instalaciones son de primer nivel. Recomiendo ampliamente el turismo médico en Mérida con este gran cirujano.",
    weightLost: "41 kg",
    timeAgo: "Hace 5 meses",
  },
];
