import type { Testimonial } from "@/types";

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "testimonial-001",
    name: "MCR",
    rating: 5,
    text: "Acudí para una segunda opinión y me dio mucha confianza la manera en la que me explicó mi problema, noté que domina muy bien el tema y me operé con él, lo recomiendo sin duda.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-002",
    name: "Alejandra Reyes Coronado",
    rating: 5,
    text: "La atención fue de calidad, fue puntual y profesional. Lo recomiendo.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-003",
    name: "AMDC",
    rating: 5,
    text: "Excelente atención, explicación clara y entendible. Muy formal el doctor.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-004",
    name: "DRH",
    rating: 5,
    text: "El doctor es muy profesional y el mejor explicando el padecimiento. Resolvió todas mis dudas y el tratamiento que me dio fue el indicado. Sin duda lo recomiendo.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-005",
    name: "BR",
    rating: 5,
    text: "Puntual y con buena disposición. Atento y empático, se toma el tiempo para explicar tu enfermedad y el tratamiento que requieres.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-006",
    name: "Miguel Ángel Pérez Cruz",
    rating: 5,
    text: "Después de mi cirugía de hernia, la recuperación fue muy rápida y el seguimiento cercano, gran empatía del doctor Mario. Muy agradecido por la atención.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-007",
    name: "Daniela Torres Hernandez",
    rating: 5,
    text: "Muy buena experiencia. Fui atendido por una hernia y el trato fue impecable, siempre explicando todo con calma.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-008",
    name: "Paola Camacho",
    rating: 5,
    text: "El doctor se toma su tiempo para explicar a detalle la enfermedad y cómo realizará la cirugía. Muy contenta con su servicio.",
    timeAgo: "Noviembre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-009",
    name: "Majo Padilla",
    rating: 5,
    text: "Muy agradecida por el trato a mi papá en su cirugía de urgencia.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-010",
    name: "Alejandro Ramirez García",
    rating: 5,
    text: "El doctor Mario fue muy respetuoso y atento durante la explicación de mi enfermedad, después de la cirugía las molestias fueron mínimas. Lo recomiendo mucho.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-011",
    name: "Paola Sánchez Morales",
    rating: 5,
    text: "Muy buena experiencia en mi cirugía. El doctor Mario transmite seguridad y confianza. Muy agradecida.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-012",
    name: "J. R.",
    rating: 5,
    text: "El Dr. Mario es muy profesional y humano. Me explicó todo con claridad, me dio mucha confianza y el tratamiento fue excelente. Lo recomiendo ampliamente.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-013",
    name: "Lilia",
    rating: 5,
    text: "El doctor fue muy empático y su explicación muy detallada. Resolvió todas mis dudas y se aseguró de que pudiera entender todo. Sin duda lo recomiendo.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-014",
    name: "MP",
    rating: 5,
    text: "Es un especialista que realmente pone interés en hacer lo mejor para la atención de sus pacientes a quienes valora y da lo mejor de sí en cada ocasión.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-015",
    name: "Eduardo Vélez",
    rating: 5,
    text: "Muy buena atención del Dr. Ruvalcaba. Me explicó los detalles del tratamiento y fue eficaz.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-016",
    name: "Francisco Javier García Pérez",
    rating: 5,
    text: "El doctor fue muy respetuoso y atento en todo momento. Lo recomiendo mucho.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-017",
    name: "M.H.G.",
    rating: 5,
    text: "Me agradó mucho el cómo explicó detalladamente todos los posibles escenarios. Agradezco la atención tan cálida.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-018",
    name: "G. C. H.",
    rating: 5,
    text: "Me hicieron una reparación de hernia inguinal y todo fue excelente, las cicatrices no se notan. Muy agradecida.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-019",
    name: "Eduardo Morales Torres",
    rating: 5,
    text: "Muy humano y profesional. Después de mi cirugía me explicó cada paso del proceso y eso me dio mucha confianza. Lo recomiendo ampliamente.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-020",
    name: "Ricardo Castillo Martínez",
    rating: 5,
    text: "Excelente cirujano, me trató por un problema de vesícula complicado y gracias a su profesionalismo todo salió perfecto.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-021",
    name: "María Fernanda Hernández López",
    rating: 5,
    text: "Tuve que operarme de apendicitis y agradezco la rapidez y seguridad con la que me atendieron. Trato cálido y muy humano.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-022",
    name: "José Luis González Pérez",
    rating: 5,
    text: "Excelente atención, me operaron de vesícula y en todo momento me sentí acompañado. El doctor siempre resolvió mis dudas con paciencia.",
    timeAgo: "Octubre 2025",
    source: "Doctoralia",
  },
  {
    id: "testimonial-023",
    name: "Andrea",
    rating: 5,
    text: "Muy buen profesional. Explica todo con detalle, fácil de entender y resuelve todas las dudas que tenga uno.",
    timeAgo: "Septiembre 2025",
    source: "Doctoralia",
  },
];
